import type { SxProps, Theme } from '@mui/material'
import { C } from '../../theme/theme'

export const navbarStyles: Record<string, SxProps<Theme>> = {
  appBar: {
    bgcolor: `${C.paper}E0`,
    backdropFilter: 'saturate(140%) blur(12px)',
    WebkitBackdropFilter: 'saturate(140%) blur(12px)',
    borderBottom: `1px solid ${C.line}80`,
    boxShadow: '0 1px 0 rgba(255,255,255,0.6) inset',
  },
  toolbar: {
    maxWidth: 1570,
    width: '100%',
    mx: 'auto',
    px: { xs: 2, sm: 3 },
    py: '5px',
    justifyContent: 'space-between',
    minHeight: { xs: 64, md: 72 },
  },
  brandBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    cursor: 'pointer',
    textDecoration: 'none',
    minWidth: 0,
    overflow: 'hidden',
  },
  brandText: {
    fontFamily: '"Blue Mirage", serif',
    fontSize: { xs: 20, md: 24 },
    lineHeight: 1.05,
    color: C.espresso,
    fontWeight: 500,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  brandSub: {
    display: 'block',
    fontSize: 18,
    color: C.espresso,
    fontStyle: 'normal',
    letterSpacing: '0.02em',
    fontFamily: '"Blue Mirage", "Inter", sans-serif',
  },
  desktopNav: {
    display: 'flex',
    gap: { md: 0.5, lg: 1 },
    alignItems: 'center',
  },
  navButton: {
    fontSize: 16,
    fontWeight: 500,
    fontFamily: '"Blue Mirage", serif',
    color: C.espresso,
    px: 1.5,
    py: 0.75,
    borderRadius: '6px',
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      left: 12,
      right: 12,
      bottom: 4,
      height: '1px',
      background: `${C.line2}88`,
      transform: 'scaleX(0)',
      transformOrigin: 'left',
      transition: 'transform .25s ease',
    },
    '&:hover::after': { transform: 'scaleX(1)' },
    '&:hover': { bgcolor: 'transparent', color: C.espresso },
  },
  registerButton: {
    ml: 1.5,
    fontWeight: 600,
    boxShadow: `0 4px 14px rgba(156,107,46,0.28)`,
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: `0 8px 22px rgba(156,107,46,0.36)`,
    },
  },
  drawerBox: {
    width: 'min(360px, 86vw)',
    pt: 1,
    background: C.paper,
    height: '100%',
  },
  drawerLink: {
    padding: '14px 12px',
    borderRadius: '10px',
    fontSize: 16,
    fontWeight: 500,
    color: C.espresso,
    '&:hover': { background: C.paper2 },
  },
  iconColor: {
    color: C.espresso,
  },
}
